version: "3"
services: 
    torproxy:
        image: dperson/torproxy
        container_name: torproxy
        environment: 
            - TOR_NewCircuitPeriod=10
            - TOR_MaxCircuitDirtiness=60
        ports: 
            - 8118:8118
            - 9050:9050
    redis:
        image: redis
        container_name: scraper-redis
    functions-vietstock:
        build: .
        container_name: functions-vietstock
        command: wait-for-it -s torproxy:8118 -s scraper-redis:6379 -t 600  -- /bin/bash
        stdin_open: true
        tty: true
        environment: 
            - REDIS_HOST=scraper-redis
            - PROXY=yes
            - TORPROXY_HOST=torproxy
            - USER_COOKIE=E5E9748A0E17EB6436DAA8F91168B3A0BD0BD247F065902F34F04EFA14404B698D1924BEFC249D2936EB3ADEEBAC694591F055B237E1C4BE83C6BAD6CFA14E28AF88EF037BDA4D641E9EFC2D941DEA9CB6553A683A670859292E64850FD0D8397A6010DBA27575578C7F37F7A955038DFB7B9E0D6632C38CA5A1124D4DFF6761
        depends_on: 
            - torproxy
            - redis
        volumes:
            - ./functions_vietstock/logs:/opt/functions_vietstock/logs
            - ./functions_vietstock/localData:/opt/functions_vietstock/localData
            - ./functions_vietstock/schemaData:/opt/functions_vietstock/schemaData
