version: "3"
services: 
    torproxy:
        image: dperson/torproxy
        container_name: torproxy
        environment: 
            - TOR_NewCircuitPeriod=10
            - TOR_MaxCircuitDirtiness=60
        ports: 
            - 8118:8118
            - 9050:9050
    redis:
        image: redis
        container_name: scraper-redis
    functions-vietstock:
        build: .
        container_name: functions-vietstock
        command: wait-for-it -s torproxy:8118 -s scraper-redis:6379 -t 600  -- bash
        stdin_open: true
        tty: true
        environment: 
            - REDIS_HOST=scraper-redis
            - PROXY=yes
            - TORPROXY_HOST=torproxy
            - USER_COOKIE=
        depends_on: 
            - torproxy
            - redis
        volumes:
            - ./functions_vietstock/logs:/opt/functions_vietstock/logs
            - ./functions_vietstock/localData:/opt/functions_vietstock/localData
